# Generated by Django 6.0.2 on 2026-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to='3d_assets/', verbose_name='3D Файл'),
        ),
    ]
