# Generated by Django 5.2.12 on 2026-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_asset_image_alter_asset_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='Скачивания'),
        ),
    ]
